// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Store.Persistance.Entities
{
    public partial class Address
    {
        public Address()
        {
            Stations = new HashSet<Station>();
        }

        public int Id { get; set; }
        public string CityName { get; set; }
        public string CountryName { get; set; }
        public string PostCode { get; set; }
        public string State { get; set; }
        public string StreetName { get; set; }
        public string StreetNumber { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }

        public virtual ICollection<Station> Stations { get; set; }
    }
}