// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Store.Persistance.Entities
{
    public partial class Currency : EntityBase
    {
        public Currency()
        {
            Prices = new HashSet<Price>();
        }

        public string Name { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
    }
}