// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Store.Persistance.Entities
{
    public partial class Person
    {
        public Person()
        {
            PersonVehicules = new HashSet<PersonVehicule>();
        }

        public int Id { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime? ModificationDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string UserName { get; set; }
        public int? StatusId { get; set; }

        public virtual PersonStatus Status { get; set; }
        public virtual ICollection<PersonVehicule> PersonVehicules { get; set; }
    }
}