// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Store.Persistance.Entities
{
    public partial class PersonRole
    {
        public PersonRole()
        {
            PersonVehicules = new HashSet<PersonVehicule>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<PersonVehicule> PersonVehicules { get; set; }
    }
}