// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Store.Persistance.Entities
{
    public partial class VehiculeType
    {
        public VehiculeType()
        {
            Vehicules = new HashSet<Vehicule>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Vehicule> Vehicules { get; set; }
    }
}