// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Store.Persistance.Entities
{
    public partial class VehiculeState
    {
        public int Id { get; set; }
        public DateTime CreationDate { get; set; }
        public int VehiculeId { get; set; }
        public int? OccupedSeat { get; set; }
        public int? CapasitySeat { get; set; }
        public decimal? Longitude { get; set; }
        public decimal? Latitude { get; set; }

        public virtual Vehicule Vehicule { get; set; }
    }
}