// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Shop.Application.Domains
{
    public partial class PanierProductModel
    {
        public int ProductId { get; set; }
        public int PanierId { get; set; }
        public DateTime CreationDate { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public DateTime? ModificationDate { get; set; }
    }
}