// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Shop.Application.Domains
{
    public partial class ProductModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public decimal? OldPrice { get; set; }
        public decimal? NewPrice { get; set; }
        public int? AvailibilityCount { get; set; }
        public int? Discount { get; set; }
        public int? RatingsCount { get; set; }
        public int? RatingsValue { get; set; }
        public string[] Color { get; set; }
        public string[] Size { get; set; }
        public int Weight { get; set; }
        public Image[] Images { get; set; }
        public string Description { get; set; }
    }

    public enum RelatedProductDataEnum
    {
        CATEGORY = 0,
        COLOR=1,
        VINTAGE=2,
        ORINALITY=3,
        REGION=4,
        COUNTRY=5,
        VOLUME=6,
        TASTE=7,
        CONSERVATION=8,
        OTHER=9
    }
}