// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Store.Persistance.Entities
{
    public partial class Currency
    {
        public Currency()
        {
            Prices = new HashSet<Price>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Price> Prices { get; set; }
    }
}