// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Store.Persistance.Entities
{
    public partial class Person
    {
        public Person()
        {
            Addresses = new HashSet<Addresse>();
            PersonRoles = new HashSet<PersonRole>();
            Products = new HashSet<Product>();
        }

        public long Id { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public string PhoneNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DiplayName { get; set; }
        public int? PersonTypeId { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? ModificationDate { get; set; }
        public string StoragePath { get; set; }

        public virtual PersonType PersonType { get; set; }
        public virtual ICollection<Addresse> Addresses { get; set; }
        public virtual ICollection<PersonRole> PersonRoles { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}