// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Store.Persistance.Entities
{
    public partial class PersonType : EntityBase
    {
        public PersonType()
        {
            People = new HashSet<Person>();
        }

        public string Name { get; set; }

        public virtual ICollection<Person> People { get; set; }
    }
}