// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Store.Persistance.Entities
{
    public partial class Price : EntityBase
    {
    
        public double? Amount { get; set; }
        public int? CurrencyId { get; set; }
        public long? ProductId { get; set; }

        public virtual Currency Currency { get; set; }
        public virtual Product Product { get; set; }
    }
}