// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Store.Persistance.Entities
{
    public partial class Product
    {
        public Product()
        {
            Prices = new HashSet<Price>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? ModiicationDate { get; set; }
        public int? ProductTypeId { get; set; }
        public int? Quality { get; set; }
        public string StoragePath { get; set; }
        public long OwnerId { get; set; }

        public virtual Person Owner { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
    }
}