// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Store.Persistance.Entities
{
    
    public partial class Role : EntityBase
    {
        public Role()
        {
            PersonRoles = new HashSet<PersonRole>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<PersonRole> PersonRoles { get; set; }
    }
}