// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Shop.Persistance.Entities
{
    public partial class PanierProduct
    {
        public int ProductId { get; set; }
        public int PanierId { get; set; }
        public DateTime CreationDate { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public DateTime? ModificationDate { get; set; }

        public virtual Panier Panier { get; set; }
        public virtual Product Product { get; set; }
    }
}