// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Shop.Persistance.Entities
{
    public partial class Product
    {
        public Product()
        {
            PanierProducts = new HashSet<PanierProduct>();
        }

        public int Id { get; set; }
        public string Reference { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime? ModificationDate { get; set; }
        public decimal? NewPrice { get; set; }
        public int? AvailibilityCount { get; set; }
        public string PicturesPath { get; set; }
        public int? ColorId { get; set; }
        public int? VintageId { get; set; }
        public int? OriginalityId { get; set; }
        public int? RegionId { get; set; }
        public int? CountryId { get; set; }
        public int? VolumeId { get; set; }
        public int? TasteId { get; set; }
        public int? ConservationId { get; set; }
        public decimal? OldPrice { get; set; }
        public int? Discount { get; set; }
        public int? RatingsCount { get; set; }
        public int? RatingsValue { get; set; }

        public virtual Category Category { get; set; }
        public virtual Color Color { get; set; }
        public virtual Conservation Conservation { get; set; }
        public virtual Country Country { get; set; }
        public virtual Originality Originality { get; set; }
        public virtual Region Region { get; set; }
        public virtual Taste Taste { get; set; }
        public virtual Vintage Vintage { get; set; }
        public virtual Volume Volume { get; set; }
        public virtual ICollection<PanierProduct> PanierProducts { get; set; }
    }
}